ALTER TABLE UTILISATEURS
    ALTER COLUMN pseudo varchar(50)
ALTER TABLE UTILISATEURS
    ALTER COLUMN nom varchar(50)
ALTER TABLE UTILISATEURS
    ALTER COLUMN prenom varchar(50)
ALTER TABLE UTILISATEURS
    ALTER COLUMN email varchar(50)
ALTER TABLE UTILISATEURS
    ALTER COLUMN rue varchar(50)
ALTER TABLE UTILISATEURS
    ALTER COLUMN ville varchar(50)